
import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from './components/navigation'
import { NextAuthProvider } from './providers/nextAuthProvider'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: process.env.NODE_ENV === 'production' ? 'Production | Yu-Gi-Oh! Meta' : 'Development | Yu-Gi-Oh! Meta',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <Navigation />
          <main>
            {children}
          </main>
        </NextAuthProvider>
      </body>

    </html>
  )
}
